#!/bin/bash

subtrees=(
	"jamespharaoh:jpstack-api:src/wbs/api"
	"jamespharaoh:jpstack-common:common"
	"jamespharaoh:jpstack-console:src/wbs/console"
	"jamespharaoh:jpstack-framework:src/wbs/framework"
	"jamespharaoh:jpstack-integrations-common:src/wbs/integrations/common"
	"jamespharaoh:jpstack-message-template:src/wbs/services/messagetemplate"
	"jamespharaoh:jpstack-platform:src/wbs/platform"
	"jamespharaoh:jpstack-sms:src/wbs/sms"
	"jamespharaoh:jpstack-ticket:src/wbs/services/ticket"
	"jamespharaoh:jpstack-utils:src/wbs/utils"
	"jamespharaoh:jpstack-wallet:src/wbs/services/wallet"
	"jamespharaoh:jpstack-web:src/wbs/web"
)

# ex: noet ts=4 filetype=bash
