#!/bin/bash

BASEDIR="/home/james/wbs"
cd "$BASEDIR"

# initialise GSM modem
#/c/modeminit /dev/ttyS0

# reset outbox
#sudo -u james psql txt2 -c "UPDATE outbox SET sending = NULL WHERE sending IS NOT NULL"

# reset exceptions
#sudo -u james psql txt2 -c "SELECT exception_clear_alerts ('daemon')"

# setup classpath

CLASSPATH="$BASEDIR/work/bin"

for filename in lib/*.jar; do
	CLASSPATH="$CLASSPATH:$filename";
done

export CLASSPATH

# setup wbs

export WBS_CONFIG=live
export WBS_CONFIG_XML=$BASEDIR/conf/wbs-$WBS_CONFIG-config.xml

# run command

exec java $JAVA_OPTS \
	wbs.platform.application.tools.BeanRunner \
	wbs-apn \
	wbs.apn \
	utils,config,data,entity,schema,sql,model,hibernate,object,logic,daemon \
	hades,hibernate \
	wbs.platform.daemon.DaemonRunner \
	runDaemon
