#!/bin/bash

fix-whitespace-aggressive \
	$(
		find src \
			-name '*.java' \
			-o -name '*.xml' \
			-o -name '*.sql' \
			-o -name '*.js' \
			-type f
	) \
	$(
		find etc \
			-type f
	) \
	$(
		find wbs-build.xml \
			-type f
	)
