#!/bin/bash

fix-whitespace \
	$(
		find src \
			-name '*.java' \
			-o -name '*.xml' \
			-o -name '*.sql' \
			-o -name '*.js' \
			-type f
	) \
	$(
		find etc \
			-type f
	) \
	$(
		find build.xml wbs-build.xml \
			-type f
	)
