#!/usr/bin/env ruby

COLOURS = {
	:default => "255",
	:debug => "244",
	:info => "039",
	:warning => "226",
	:error => "203",
}

MAPPINGS = {
	/DEBUG/ => :debug,
	/INFO/ => :info,
	/WARN/ => :warning,
	/ERROR/ => :error,
}

while line = STDIN.gets.strip

	colour_name = :default

	MAPPINGS.each do
		|this_regex, this_colour_name|

		next unless line =~ this_regex

		colour_name =
			this_colour_name

		break

	end

	unless COLOURS[colour_name]
		colour_name = :default
	end

	colour_code =
		COLOURS[colour_name]

	STDOUT.print [
		"\e[38;5;#{colour_code}m",
		line,
		"\e[0m",
		"\n",
	].join ""

end
