#!/bin/bash

set -euf -o pipefail

today="$(date +'%Y-%m-%d' --date='-0 days')"
yesterday="$(date +'%Y-%m-%d' --date='-1 days')"

lock="/backup/lock"

basebackup_enabled="yes"
basebackup_path="/backup/backups/platform-database-basebackup"
basebackup_name="platform-database-basebackup"
basebackup_today="$basebackup_path/$basebackup_name-$today.tar"
basebackup_yesterday="$basebackup_path/$basebackup_name-$yesterday.tar"

dump_path="/backup/backups/platform-database-dump"
dump_name="platform-database-basebackup"
dump_enabled="no"
dump_today="$dump_path/$dump_name-$today.sql"
dump_yesterday="$dump_path/$dump_name-$yesterday.sql"

exec 200>"$lock"
flock --exclusive 200

if test -e $basebackup_today; then

	echo "Already done a basebackup today"

elif test -e $dump_today; then

	echo "Already done a dump today"

elif test "$basebackup_enabled" = "yes" -a \! -e "$basebackup_yesterday"; then

	echo "Performing base backup"

	mkdir -p "$basebackup_path"

	time {

		echo "========== BEGIN BACKUP =========="

		lxc-attach --name "zuri-platform-database-32bit" -- \
		sudo -H -u "ubuntu" \
		psql "txt2" -c "select pg_start_backup ('$today');"

		echo "========== PERFORM BACKUP =========="

		{

			tar \
				--create \
				--verbose \
				--one-file-system \
				--warning=no-file-ignored \
				--warning=file-changed \
				--directory "/mnt/zuri-platform-database-data/8.3/main" \
				--exclude "./pg_xlog" \
				"." \
			|| test "$?" -eq "1"

		} | {

			sudo -H -u ubuntu -- \
			zbackup \
				--password-file "/backup/password" \
				--silent \
				backup \
				"$basebackup_today"

		}

		echo "========== END BACKUP =========="

		lxc-attach --name "zuri-platform-database-32bit" -- \
		sudo -H -u "ubuntu" \
		psql "txt2" -c "select pg_stop_backup ();"

		echo "========== DONE =========="

	}

elif test "$dump_enabled" = "yes" -a \! -e "$dump_yesterday"; then

	echo "Performing SQL dump"

	mkdir -p "$dump_path"

	time {

		{

			lxc-attach --name "zuri-platform-database-32bit" -- \
			sudo -H -u "ubuntu" -- \
			pg_dump "txt2" \

		} | {

			sudo -H -u ubuntu -- \
			zbackup \
				--password-file "/backup/password" \
				--silent \
				backup \
				"$dump_today"

		}

	}

else

	echo "Nothing to do"

fi

# ex: noet ts=4 filetype=bash
