#!/bin/sh

timeout_start="60"
timeout_stop="15"
timeout_kill="5"

tomcat_home="/home/ubuntu/tomcat/platform-console-current"
tomcat_port="9001"

upstart_service="platform-console-current"

function service_hook_is_running_1 {

	ps ax \
		| grep -v "grep" \
		| grep -q -- " -Dcatalina.base=$tomcat_home "

}

function service_hook_is_running_2 {

	$BASEDIR/c/socktest localhost "$tomcat_port"

}

function service_hook_start {

	sudo /sbin/start "$upstart_service"

}

function service_hook_stop {

	sudo /sbin/stop "$upstart_service"

}

function service_hook_kill {

	kill -kill $(
		ps ax \
		| grep -v "grep" \
		| grep -- " -Dcatalina.base=$tomcat_home " \
		| cut -d' ' -f1
	)

}

# ex: noet ts=4 filetype=bash
