#!/bin/sh

cd $BASEDIR

timeout_start="5"
timeout_stop="5"
timeout_kill="5"

upstart_service="platform-daemon-live"

function service_hook_is_running_1 {

	ps ax \
	| grep -v "grep" \
	| grep -q "wbs.platform.daemon.DaemonRunner"

}

function service_hook_is_running_2 {

	true

}

function service_hook_start {

	sudo /sbin/start "$upstart_service"

}

function service_hook_stop {

	sudo /sbin/stop "$upstart_service"

}

function service_hook_kill {

	kill -kill $(cat daemon.pid)

}
