#!/bin/sh

tomcat_api_start_timeout=60
tomcat_api_stop_timeout=15
tomcat_api_kill_timeout=5

function tomcat_api_is_running_1 {
	ps ax | grep Dcatalina.base=/home/ubuntu/tomcat-api | grep -v grep >/dev/null
}

function tomcat_api_is_running_2 {
	$BASEDIR/c/socktest localhost 9080
}

function tomcat_api_start {
	sudo start platform-live-api
}

function tomcat_api_stop {
	sudo stop platform-live-api
}

function tomcat_api_kill {
	kill -kill $(ps ax | grep Dcatalina.base=/home/ubuntu/tomcat-api | grep -v grep | cut -d' ' -f1)
}
