#!/bin/sh

tomcat_console_start_timeout=60
tomcat_console_stop_timeout=15
tomcat_console_kill_timeout=5

function tomcat_console_is_running_1 {
	ps ax \
		| grep -- -Dcatalina.base=/home/ubuntu/tomcat-console \
		| grep -v console-test \
		| grep -v grep >/dev/null
}

function tomcat_console_is_running_2 {
	$BASEDIR/c/socktest localhost 8080
}

function tomcat_console_start {
	sudo start platform-live-console
}

function tomcat_console_stop {
	sudo stop platform-live-console
}

function tomcat_console_kill {
	kill -kill $(ps ax | grep Dcatalina.base=/home/ubuntu/tomcat-console | grep -v grep | cut -d' ' -f1)
}
