#!/bin/bash

JAVA_HOME=/home/ubuntu/java/jdk1.8.0_65
PATH=$JAVA_HOME/bin:$PATH

BASEDIR="/home/ubuntu/wbs-hades"
cd "$BASEDIR"

# initialise GSM modem
#/c/modeminit /dev/ttyS0

# set java

JAVA_OPTS="-Xmx2096m"
JAVA_OPTS="$JAVA_OPTS -XX:-OmitStackTraceInFastThrow"

# setup classpath

CLASSPATH="$BASEDIR/work/bin"

for filename in lib/*.jar; do
	CLASSPATH="$CLASSPATH:$filename";
done

export CLASSPATH

# setup wbs

export WBS_CONFIG="live"
export WBS_CONFIG_XML="$BASEDIR/conf/wbs-$WBS_CONFIG-config.xml"

# run command

exec java $JAVA_OPTS \
	wbs.framework.application.tools.BeanRunner \
	wbs-apn \
	wbs.apn \
	agent,config,data,logic,model,model-meta,entity,schema,sql,hibernate,object,utils \
	hades,hibernate,daemon \
	wbs.platform.daemon.DaemonRunner \
	runDaemon
