#!/bin/bash

set -euf -o pipefail

CONFIG=$(mktemp)

api_command=$(
	echo -n "export WBS_CONFIG_XML=config/wbs-api-config.xml;"
	echo -n "sleep 0;"
	echo -n "ant just-api-test;"
	echo -n "read;"
)

console_command=$(
	echo -n "export WBS_CONFIG_XML=config/wbs-console-config.xml;"
	echo -n "sleep 1;"
	echo -n "ant just-console-test;"
	echo -n "read;"
)

daemon_command=$(
	echo -n "export WBS_CONFIG_XML=config/wbs-daemon-config.xml;"
	echo -n "sleep 2;"
	echo -n "ant just-daemon-test;"
	echo -n "read;"
)

cat >$CONFIG <<-END

	termcapinfo xterm* ti@:te@

	bindkey ^[[5;5~ eval "copy" "stuff ^U"
	bindkey ^[[6;5~ eval "copy" "stuff ^D"

	mousetrack on

	split
	split

	screen -t api bash -c "$api_command"
	screen -t console bash -c "$console_command"
	screen -t daemon bash -c "$daemon_command"

	select api

	focus down
	select console

	focus down
	select daemon

END

trap "rm $CONFIG" EXIT

ant build just-console-deploy just-api-deploy just-daemon-deploy

screen -c "$CONFIG"

# ex: noet ts=4 filetype=bash
