#!/bin/bash

set -e

rm -f binaries/libraries/*

java -jar \
	"/usr/share/java/ivy.jar" \
	-ivy "etc/ivy.xml" \
	-retrieve "binaries/libraries/[artifact]-[type]-[revision].[ext]"

cd lib
rm -f *
ln -s ../binaries/libraries/* .
